-- migrations/002_seed_ham.sql
-- 16 parameter HAM dari buku Landmark Decisions (LeIP/NCHR 2024)

INSERT OR REPLACE INTO ham_parameters VALUES
('HAM-01','Hak atas Bantuan Hukum','Pendampingan Penasihat Hukum',
'Tuntutan penuntut umum tidak dapat diterima apabila tidak terdapat penasihat hukum yang mendampingi tersangka/terdakwa pada tahap penyidikan, padahal tersangka/terdakwa wajib didampingi penasihat hukum berdasarkan Pasal 56 KUHAP.',
'Fair trial — Hak atas Bantuan Hukum',
'["Pasal 56 KUHAP","UUD 1945 Pasal 28D ayat (1)","UU No. 39 Tahun 1999 Pasal 17 dan 18 ayat (4)"]',
'["ICCPR Pasal 14 ayat (3)(d)","UN General Comment No. 32","UN Principles on Access to Legal Aid"]',
'["bantuan hukum","penasihat hukum","pendampingan","penyidikan","fair trial","tidak dapat diterima"]',
'01/PutHAM/Pidana/2024'),

('HAM-02','Hak atas Bantuan Hukum','Kehadiran Fisik Penasihat Hukum',
'Penasihat hukum yang hanya menandatangani BAP tanpa hadir mendampingi secara fisik tidak memenuhi syarat bantuan hukum. Keterangan yang diperoleh tanpa pendampingan fisik tidak dapat digunakan sebagai bukti.',
'Fair trial — Hak atas Bantuan Hukum Efektif',
'["Pasal 54, 55, 56 KUHAP"]',
'["ICCPR Pasal 14 ayat (3)(d)","UN General Comment No. 32 par. 34 dan 38"]',
'["penasihat hukum","tandatangan BAP","tidak hadir","pendampingan fisik","bukti tidak sah"]',
'02/PutHAM/Pidana/2024'),

('HAM-03','Hak atas Bantuan Hukum','Bantuan Hukum bagi Anak',
'Pendampingan hukum bagi Anak pada setiap tahapan pemeriksaan bersifat imperatif/wajib menurut Pasal 23 ayat (1) UU No. 11 Tahun 2012 tentang SPPA, meskipun Anak menolak untuk didampingi.',
'Fair trial — Hak Anak — Hak atas Bantuan Hukum',
'["Pasal 23 ayat (1) UU No. 11 Tahun 2012 tentang SPPA"]',
'["Convention on the Rights of the Child Pasal 40 ayat (2)","UN General Comment No. 32 par. 42","Beijing Rules 15.1"]',
'["anak","peradilan anak","SPPA","pendampingan wajib","hak anak"]',
'04/PutHAM/Pidana/2024'),

('HAM-04','Larangan Penyiksaan','Keterangan dari Penyiksaan sebagai Bukti',
'Keterangan terdakwa pada tahap penyidikan yang terbukti diperoleh dengan penyiksaan dan tanpa pendampingan penasihat hukum tidak dapat digunakan sebagai bukti dalam persidangan.',
'Fair trial — Larangan Penyiksaan',
'["Pasal 66 KUHAP","UUD 1945 Pasal 28G ayat (2)","UU No. 39 Tahun 1999 Pasal 33 ayat (1)"]',
'["ICCPR Pasal 7 dan 14","UDHR Pasal 5","CAT (Konvensi Anti Penyiksaan)"]',
'["penyiksaan","torture","keterangan tidak sah","bukti tidak dapat digunakan","BAP penyiksaan"]',
'05/PutHAM/Pidana/2024'),

('HAM-05','Larangan Penyiksaan','Beban Pembuktian Penyiksaan',
'Beban pembuktian terjadinya penyiksaan tidak dapat dibebankan kepada terdakwa karena terdakwa tidak dibebani kewajiban pembuktian sesuai Pasal 66 KUHAP.',
'Fair trial — Asas Praduga Tak Bersalah — Larangan Penyiksaan',
'["Pasal 66 KUHAP"]',
'["ICCPR Pasal 14 ayat (2)","UN General Comment No. 32"]',
'["beban pembuktian","terdakwa","penyiksaan","praduga tak bersalah","Pasal 66 KUHAP"]',
'06/PutHAM/Pidana/2024'),

('HAM-06','Hak atas Juru Bahasa','Penerjemah dalam Persidangan',
'Terdakwa yang tidak memahami bahasa Indonesia berhak mendapatkan penerjemah dalam setiap tahap pemeriksaan. Pemeriksaan tanpa penerjemah melanggar fair trial.',
'Fair trial — Hak atas Penerjemah',
'["Pasal 53 KUHAP"]',
'["ICCPR Pasal 14 ayat (3)(f)","UN General Comment No. 32 par. 40"]',
'["juru bahasa","penerjemah","interpreter","bahasa asing","tidak menguasai bahasa Indonesia"]',
'11/PutHAM/Pidana/2024'),

('HAM-07','Pelaksanaan Upaya Paksa','Penggeledahan',
'Penggeledahan yang dilakukan tanpa surat izin yang sah dari pengadilan merupakan tindakan melawan hukum dan bukti yang diperoleh tidak dapat digunakan.',
'Hak atas Privasi — Fair trial — Larangan Bukti Ilegal',
'["Pasal 33-37 KUHAP","UUD 1945 Pasal 28G"]',
'["ICCPR Pasal 17","UDHR Pasal 12"]',
'["penggeledahan","surat izin","tidak sah","bukti ilegal","privasi","tanpa izin pengadilan"]',
'12/PutHAM/Pidana/2024'),

('HAM-08','Pelaksanaan Upaya Paksa','Pembelian Terselubung (Undercover Buy)',
'Teknik pembelian terselubung hanya sah apabila dilakukan sesuai prosedur. Teknik penyamaran yang memprovokasi terdakwa untuk melakukan tindak pidana (entrapment) tidak dapat dibenarkan.',
'Fair trial — Larangan Provokasi — Legalitas Investigasi',
'["UU No. 35 Tahun 2009 tentang Narkotika"]',
'["ICCPR Pasal 14","ECtHR Teixeira de Castro v. Portugal"]',
'["undercover buy","pembelian terselubung","penyamaran","entrapment","provokasi","teknik investigasi khusus"]',
'15/PutHAM/Pidana/2024'),

('HAM-09','Hak atas Saksi','Pemeriksaan Saksi yang Adil',
'Terdakwa berhak untuk menghadirkan saksi yang menguntungkan (a de charge) dan memeriksa saksi yang memberatkan (a charge). Pembatasan hak ini melanggar prinsip fair trial.',
'Fair trial — Hak atas Pemeriksaan Saksi',
'["Pasal 65 KUHAP","UUD 1945 Pasal 28D"]',
'["ICCPR Pasal 14 ayat (3)(e)","UN General Comment No. 32 par. 39"]',
'["saksi","a de charge","a charge","saksi menguntungkan","saksi memberatkan","pemeriksaan saksi"]',
'19/PutHAM/Pidana/2024'),

('HAM-10','Pemeriksaan Fisik dan Forensik','Pemeriksaan Urine/DNA/Darah',
'Pemeriksaan urine, DNA, atau darah tanpa persetujuan terdakwa atau tanpa prosedur yang sah dapat melanggar hak atas privasi. Hasil pemeriksaan yang diperoleh secara tidak sah tidak dapat digunakan sebagai bukti.',
'Hak atas Privasi — Martabat Manusia — Fair trial',
'["UUD 1945 Pasal 28G","KUHAP"]',
'["ICCPR Pasal 7 dan 17","UDHR Pasal 12"]',
'["urine","tes urine","DNA","darah","tes darah","pemeriksaan forensik","tanpa persetujuan"]',
'22/PutHAM/Pidana/2024'),

('HAM-11','Dakwaan dan Keabsahan Bukti','Syarat Dakwaan',
'Dakwaan harus memenuhi syarat formil dan materiil. Dakwaan yang tidak memenuhi syarat dapat dinyatakan batal demi hukum atau tidak dapat diterima.',
'Fair trial — Hak untuk Diberitahu Dakwaan — Legalitas',
'["Pasal 143 KUHAP","Pasal 156 KUHAP"]',
'["ICCPR Pasal 14 ayat (3)(a)","UN General Comment No. 32 par. 31"]',
'["dakwaan","batal demi hukum","syarat dakwaan","tidak dapat diterima","eksepsi","dakwaan tidak sah"]',
'26/PutHAM/Pidana/2024'),

('HAM-12','Pemidanaan','Proporsionalitas Pemidanaan',
'Penjatuhan pidana harus memperhatikan proporsionalitas antara berat ringannya tindak pidana dengan sanksi yang dijatuhkan, serta mempertimbangkan keadaan yang meringankan dan memberatkan.',
'Proporsionalitas — Larangan Hukuman Kejam — Rehabilitasi',
'["KUHP","UUD 1945 Pasal 28G ayat (2)"]',
'["ICCPR Pasal 7","UDHR Pasal 5","UN Standard Minimum Rules"]',
'["proporsionalitas","pemidanaan","keadaan meringankan","keadaan memberatkan","rehabilitasi"]',
'28/PutHAM/Pidana/2024'),

('HAM-13','Non-Diskriminasi dan Kelompok Rentan','Diskriminasi dalam Perkara',
'Setiap orang berhak mendapatkan perlakuan yang sama di hadapan hukum tanpa diskriminasi berdasarkan ras, agama, etnis, jenis kelamin, atau status lainnya.',
'Non-Diskriminasi — Persamaan di Depan Hukum',
'["UUD 1945 Pasal 28I ayat (2)","UU No. 39 Tahun 1999 Pasal 3"]',
'["ICCPR Pasal 2 dan 26","UDHR Pasal 7","ICERD"]',
'["diskriminasi","non-diskriminasi","kelompok rentan","minoritas","ras","agama","etnis","persamaan hukum"]',
'03/PutHAM/Perdata/2024'),

('HAM-14','Hak Perempuan','Kesetaraan Gender dalam Hukum',
'Perempuan berhak mendapatkan perlakuan yang setara di hadapan hukum. Putusan yang mengandung bias gender atau tidak mempertimbangkan perspektif perempuan melanggar prinsip kesetaraan.',
'Kesetaraan Gender — Non-Diskriminasi — Hak Perempuan',
'["UUD 1945 Pasal 28I","UU No. 7 Tahun 1984 tentang CEDAW"]',
'["CEDAW","ICCPR Pasal 3 dan 26","UDHR Pasal 2"]',
'["perempuan","gender","kesetaraan","CEDAW","hak perempuan","bias gender","diskriminasi perempuan"]',
'04/PutHAM/Agama/2024'),

('HAM-15','Kebebasan Berekspresi','Pencemaran Nama Baik dan Kebebasan Ekspresi',
'Pembatasan kebebasan berekspresi harus: (1) diatur oleh hukum; (2) diperlukan; (3) proporsional; (4) untuk tujuan yang sah. Pemidanaan atas ekspresi yang tidak memenuhi syarat pembatasan melanggar kebebasan berekspresi.',
'Kebebasan Berekspresi — Proporsionalitas — Legalitas Pembatasan',
'["UUD 1945 Pasal 28E ayat (3)","UU No. 39 Tahun 1999 Pasal 23"]',
'["ICCPR Pasal 19","UN General Comment No. 34","Siracusa Principles"]',
'["kebebasan berekspresi","pencemaran nama baik","penghinaan","Pasal 310 KUHP","Pasal 311 KUHP","ITE","Pasal 27","pembatasan","proporsional"]',
'HAM-EKSPRESI'),

('HAM-16','Praduga Tak Bersalah','Asas Praduga Tak Bersalah',
'Terdakwa berhak dianggap tidak bersalah sampai terbukti bersalah melalui proses peradilan yang adil. Tindakan yang mengasumsikan kesalahan terdakwa sebelum putusan melanggar asas ini.',
'Praduga Tak Bersalah — Fair trial',
'["Pasal 8 UU No. 48 Tahun 2009","UUD 1945 Pasal 28D"]',
'["ICCPR Pasal 14 ayat (2)","UDHR Pasal 11","UN General Comment No. 32 par. 30"]',
'["praduga tak bersalah","presumption of innocence","tidak terbukti","bebas","dilepaskan"]',
'HAM-PRADUGA');
